#!/bin/bash

#Copie du fichier /etc/motd
cp /etc/motd /etc/motd.bak

#Debut du fichier
echo -e "########################################\n" > /etc/motd


#Nom de machine
echo -e "Bienvenue sur la machine: $HOSTNAME \n" >> /etc/motd


#Version de machine:
vers=`cat /etc/issue`
echo "- Version: $vers" >> /etc/motd


#Adresse IP
echo -e "\n- Adresse(s) IP:" >> /etc/motd
ip a | grep 192. | awk '{print $7 " " $2 " " }' >> /etc/motd


#Route par defaut
gateway=`ip route | grep default | awk '{print $3 " " $2 " " $5 }'`
echo -e "\n- Route par defaut: $gateway" >> /etc/motd
#ip route | grep default | awk '{print $1 " " $3 " " $2 " " $5 }' >> /etc/motd


#Taille disque:
#OLD
#size=`df -h | grep /dev/sda1 | awk '{print $2}'`
#rest=`df -h | grep /dev/sda1 | awk '{print $5}'`
#echo -e "\n- Taille du disque dur: $size" >> /etc/motd
#echo -e "  Utilisé à $rest" >> /etc/motd

#NEW
size=`df -h | grep /dev/sd | awk '{print "   - "$1" : "$2 " utilisé à "$5}'`
echo -e "\n- Detail des partitions:" >> /etc/motd
echo -e "$size" >> /etc/motd

#Protocole d'ecoutes:
echo -e "\n- Protocole d'ecoutes:" >> /etc/motd
netstat -lntup | grep tcp | grep -v tcp6 | awk '{print $7}' | sed -e "s/[0-9][0-9][0-9][/]//" | sed '/^$/d'>> /etc/motd
netstat -lntup | grep udp | grep -v udp6 | awk '{print $7}' | sed -e "s/[0-9][0-9][0-9][/]//" | sed '/^$/d' >> /etc/motd

#Fin du fichier
echo -e "\n########################################\n" >> /etc/motd

exit 0
